---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/medschoolproffs/public_html/
    - export ADMINPATH=/home2/medschoolproffs/admin/

    - cd /home2/medschoolproffs/repositorries/medschoolproffsog
    - pnpm install --frozen-lockfile
    - pnpm run build:student
    - pnpm run build:admin

    - /bin/cp -R artifacts/frontend-student/dist/* $DEPLOYPATH
    - /bin/cp -R artifacts/frontend-admin/dist/* $ADMINPATH