# Builds the api-server and its workspace dependencies
# and produces a small production runtime image.
#
# Build context must be the repo root:
# docker build -t medschoolproffs-api .
#
# Run:
# docker run -p 3001:3001 --env-file .env medschoolproffs-api

FROM node:22-slim AS base

RUN corepack enable

WORKDIR /repo


# ---------------------------------------------------------------------------
# Build stage
# ---------------------------------------------------------------------------

FROM base AS build

COPY . .

# Install the complete pnpm workspace
RUN pnpm install --frozen-lockfile=false

# Typecheck shared workspace libraries
RUN pnpm run typecheck:libs

# Build the API server
RUN pnpm --filter @workspace/api-server run build

# Create a production-only deployment containing the API's
# dependencies, including workspace dependencies.
RUN pnpm --filter @workspace/api-server deploy --prod /prod


# ---------------------------------------------------------------------------
# Runtime stage
# ---------------------------------------------------------------------------

FROM node:22-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production

# Production dependencies generated by pnpm deploy
COPY --from=build /prod/node_modules ./node_modules
COPY --from=build /prod/package.json ./package.json

# Compiled API server
COPY --from=build /repo/artifacts/api-server/dist ./dist

EXPOSE 3001

CMD ["node", "--enable-source-maps", "dist/index.mjs"]
