# Builds the api-server and its workspace dependencies
# and produces a production runtime image.
#
# Build context must be the repository root.
#
# Example:
# docker build -t medschoolproffs-api .
#
# Run:
# docker run -p 3001:3001 --env-file .env medschoolproffs-api


# ============================================================================
# BASE
# ============================================================================

FROM node:22-slim AS base

RUN corepack enable

WORKDIR /repo


# ============================================================================
# BUILD
# ============================================================================

FROM base AS build

# Copy the complete monorepo
COPY . .

# Install workspace dependencies
RUN pnpm install --frozen-lockfile=false

# Typecheck shared libraries
RUN pnpm run typecheck:libs

# Build the API server
RUN pnpm --filter @workspace/api-server run build

# Create a production deployment of the API.
#
# --legacy is required because this workspace does not use
# inject-workspace-packages=true.
RUN pnpm --filter @workspace/api-server deploy --prod --legacy /prod


# ============================================================================
# RUNTIME
# ============================================================================

FROM node:22-slim AS runtime

WORKDIR /app

ENV NODE_ENV=production

# Copy production dependencies generated by pnpm deploy
COPY --from=build /prod/node_modules ./node_modules

# Copy the production package manifest
COPY --from=build /prod/package.json ./package.json

# Copy the compiled API
COPY --from=build /repo/artifacts/api-server/dist ./dist

# API port
EXPOSE 3001

# Start API server
CMD ["node", "--enable-source-maps", "dist/index.mjs"]
