/**
 * MedschoolProffs AI Service
 *
 * Supports:
 * - Anthropic
 * - OpenAI
 * - Gemini
 * - OpenAI-compatible custom endpoints
 *
 * AI configuration:
 * Admin -> Platform Settings -> AI
 *
 * Environment fallbacks:
 * ANTHROPIC_API_KEY
 * OPENAI_API_KEY
 * GEMINI_API_KEY
 * AI_PROVIDER
 * CUSTOM_AI_KEY
 * CUSTOM_AI_MODEL
 * CUSTOM_AI_URL
 */

import { getSetting } from "./settings";

/* -------------------------------------------------------------------------- */
/* Errors                                                                     */
/* -------------------------------------------------------------------------- */

export class AiNotConfiguredError extends Error {
  constructor() {
    super(
      "No AI provider is configured. Set it from Admin -> Platform settings -> AI, " +
        "or set ANTHROPIC_API_KEY / OPENAI_API_KEY / GEMINI_API_KEY in the environment.",
    );

    this.name = "AiNotConfiguredError";
  }
}

/* -------------------------------------------------------------------------- */
/* Types                                                                      */
/* -------------------------------------------------------------------------- */

export interface ExplanationRequest {
  question: string;
  options: string[];
  correctAnswer: string | null;
  reference?: string | null;
}

export interface FlashcardExplanationRequest {
  front: string;
  back: string;
}

export interface FlashcardGenerationRequest {
  /**
   * Explicit source material.
   */
  sourceText?: string;

  /**
   * Optional MCQs to use as source material.
   */
  mcqs?: Array<{
    question: string;
    correctAnswer: string | null;
    explanation?: string | null;
  }>;

  /**
   * Optional topic name.
   */
  topicLabel?: string;

  /**
   * Number of cards requested.
   *
   * Supports values greater than 20.
   * Maximum supported value: 100.
   */
  count: number;
}

export interface GeneratedFlashcard {
  front: string;
  back: string;
}

interface ProviderConfig {
  provider: string;
  apiKey: string;
  model: string;
  baseUrl?: string;
}

/* -------------------------------------------------------------------------- */
/* Limits                                                                     */
/* -------------------------------------------------------------------------- */

/**
 * Maximum number of flashcards generated by one request.
 *
 * This is intentionally higher than 20.
 */
const MAX_FLASHCARDS = 100;

/**
 * Number of cards requested from the AI in one generation call.
 *
 * Keeping this around 20 makes JSON responses much more reliable.
 */
const FLASHCARD_BATCH_SIZE = 20;

/**
 * Maximum number of attempts when an AI returns fewer cards than requested.
 */
const MAX_GENERATION_ATTEMPTS = 4;

/* -------------------------------------------------------------------------- */
/* MCQ Explanation Prompt                                                     */
/* -------------------------------------------------------------------------- */

function buildPrompt({
  question,
  options,
  correctAnswer,
  reference,
}: ExplanationRequest): string {
  const optionList = options
    .map((opt, i) => `${String.fromCharCode(65 + i)}. ${opt}`)
    .join("\n");

  return [
    "You are writing a concise study explanation for a medical school MCQ (MBBS/BDS level).",

    "Explain why the correct answer is right and briefly explain why the other options are wrong.",

    "Keep the explanation factual, exam-focused, and under 150 words.",

    "Do not use markdown headers.",

    "",

    `Question: ${question}`,

    `Options:\n${optionList}`,

    correctAnswer
      ? `Correct answer: ${correctAnswer}`
      : "Correct answer: not specified — infer the most medically accurate answer and clearly state uncertainty.",

    reference
      ? `Reference material to ground the explanation in:\n${reference}`
      : "",
  ]
    .filter(Boolean)
    .join("\n");
}

/* -------------------------------------------------------------------------- */
/* Flashcard Explanation Prompt                                               */
/* -------------------------------------------------------------------------- */

function buildFlashcardPrompt({
  front,
  back,
}: FlashcardExplanationRequest): string {
  return [
    "You are helping a medical student (MBBS/BDS level) understand a flashcard.",

    "Explain the answer in a different way from the original one-line definition.",

    "Use an analogy, mechanism walkthrough, or clinical example when useful.",

    "Keep it factual and under 130 words.",

    "Do not use markdown headers.",

    "",

    `Flashcard prompt: ${front}`,

    `Flashcard answer: ${back}`,
  ].join("\n");
}

/* -------------------------------------------------------------------------- */
/* Flashcard Generation Prompt                                                */
/* -------------------------------------------------------------------------- */

function buildFlashcardGenerationPrompt({
  sourceText,
  mcqs,
  topicLabel,
  count,
}: FlashcardGenerationRequest): string {
  const source = sourceText?.trim()
    ? sourceText.trim()
    : (mcqs ?? [])
        .map(
          (m) =>
            `Q: ${m.question}\n` +
            `A: ${m.correctAnswer ?? "(unspecified)"}` +
            (m.explanation ? `\nWhy: ${m.explanation}` : ""),
        )
        .join("\n\n");

  if (!source.trim()) {
    throw new Error(
      "Flashcard generation requires source material or MCQs.",
    );
  }

  return [
    `You are creating high-quality spaced-repetition flashcards for a medical student (MBBS/BDS level)${
      topicLabel ? ` studying ${topicLabel}` : ""
    }.`,
    
    "",

    `Generate exactly ${count} different flashcard pairs.`,

    "Use ONLY the supplied source material.",

    "Do not invent facts that are not supported by the source unless a tiny amount of medically necessary wording is required for clarity.",

    "Each front must be a short, specific question or recall prompt.",

    "Each back must contain a concise, factually correct answer in 1-3 sentences.",

    "Prioritize high-yield medical facts, mechanisms, definitions, clinical correlations, investigations, treatments, complications, and distinguishing features when present in the source.",

    "Do not create near-duplicate cards.",

    "Do not repeat the same question using different wording.",

    "Do not include markdown headers.",

    "Do not include numbering inside front or back.",

    "Do not include explanations outside the JSON.",

    "",

    "Return ONLY valid JSON.",

    "Required format:",

    '[{"front":"Question","back":"Answer"}]',

    "",

    "SOURCE MATERIAL:",

    source,
  ].join("\n");
}

/* -------------------------------------------------------------------------- */
/* JSON Parsing                                                               */
/* -------------------------------------------------------------------------- */

function parseFlashcardJson(raw: string): GeneratedFlashcard[] {
  if (!raw || !raw.trim()) {
    throw new Error("AI returned an empty flashcard response.");
  }

  let cleaned = raw.trim();

  // Remove markdown code fences.
  cleaned = cleaned
    .replace(/^```(?:json)?\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();

  let parsed: unknown;

  try {
    parsed = JSON.parse(cleaned);
  } catch {
    // Sometimes an AI adds a small amount of text around the JSON.
    const start = cleaned.indexOf("[");
    const end = cleaned.lastIndexOf("]");

    if (start === -1 || end === -1 || end <= start) {
      throw new Error("AI did not return valid flashcard JSON.");
    }

    const jsonBlock = cleaned.slice(start, end + 1);

    try {
      parsed = JSON.parse(jsonBlock);
    } catch {
      throw new Error("AI did not return valid flashcard JSON.");
    }
  }

  if (!Array.isArray(parsed)) {
    throw new Error("AI did not return a flashcard array.");
  }

  const cards: GeneratedFlashcard[] = [];

  for (const item of parsed) {
    if (!item || typeof item !== "object") {
      continue;
    }

    const record = item as Record<string, unknown>;

    const front =
      typeof record.front === "string"
        ? record.front.trim()
        : String(record.front ?? "").trim();

    const back =
      typeof record.back === "string"
        ? record.back.trim()
        : String(record.back ?? "").trim();

    if (!front || !back) {
      continue;
    }

    cards.push({
      front,
      back,
    });
  }

  if (cards.length === 0) {
    throw new Error("AI returned no usable flashcards.");
  }

  return cards;
}

/* -------------------------------------------------------------------------- */
/* Duplicate Detection                                                        */
/* -------------------------------------------------------------------------- */

function normalizeText(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/gi, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function isDuplicateCard(
  candidate: GeneratedFlashcard,
  existing: GeneratedFlashcard[],
): boolean {
  const candidateFront = normalizeText(candidate.front);

  if (!candidateFront) {
    return true;
  }

  return existing.some((card) => {
    const existingFront = normalizeText(card.front);

    if (candidateFront === existingFront) {
      return true;
    }

    /*
     * Basic near-duplicate detection.
     *
     * If one question contains the other and they are very similar,
     * treat it as a duplicate.
     */
    const shorter = Math.min(
      candidateFront.length,
      existingFront.length,
    );

    const longer = Math.max(
      candidateFront.length,
      existingFront.length,
    );

    if (shorter > 30 && shorter / longer > 0.85) {
      return (
        candidateFront.includes(existingFront) ||
        existingFront.includes(candidateFront)
      );
    }

    return false;
  });
}

function addUniqueCards(
  target: GeneratedFlashcard[],
  incoming: GeneratedFlashcard[],
  limit: number,
): void {
  for (const card of incoming) {
    if (target.length >= limit) {
      break;
    }

    if (!isDuplicateCard(card, target)) {
      target.push(card);
    }
  }
}

/* -------------------------------------------------------------------------- */
/* Anthropic                                                                  */
/* -------------------------------------------------------------------------- */

async function generateWithAnthropic(
  apiKey: string,
  model: string,
  prompt: string,
  maxTokens = 5000,
): Promise<string> {
  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",

    headers: {
      "Content-Type": "application/json",
      "x-api-key": apiKey,
      "anthropic-version": "2023-06-01",
    },

    body: JSON.stringify({
      model,
      max_tokens: maxTokens,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");

    throw new Error(
      `Anthropic API error (${res.status}): ${body.slice(0, 500)}`,
    );
  }

  const data = (await res.json()) as {
    content?: Array<{
      type: string;
      text?: string;
    }>;
  };

  const text = data.content
    ?.filter((block) => block.type === "text")
    .map((block) => block.text ?? "")
    .join("");

  if (!text) {
    throw new Error("Anthropic API returned no text content.");
  }

  return text.trim();
}

/* -------------------------------------------------------------------------- */
/* OpenAI                                                                     */
/* -------------------------------------------------------------------------- */

async function generateWithOpenAi(
  apiKey: string,
  model: string,
  prompt: string,
  maxTokens = 5000,
): Promise<string> {
  const res = await fetch("https://api.openai.com/v1/chat/completions", {
    method: "POST",

    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`,
    },

    body: JSON.stringify({
      model,
      max_tokens: maxTokens,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");

    throw new Error(
      `OpenAI API error (${res.status}): ${body.slice(0, 500)}`,
    );
  }

  const data = (await res.json()) as {
    choices?: Array<{
      message?: {
        content?: string | null;
      };
    }>;
  };

  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error("OpenAI API returned no text content.");
  }

  return text.trim();
}

/* -------------------------------------------------------------------------- */
/* Gemini                                                                     */
/* -------------------------------------------------------------------------- */

async function generateWithGemini(
  apiKey: string,
  model: string,
  prompt: string,
  maxOutputTokens = 5000,
): Promise<string> {
  const cleanModel = model.replace(/^models\//, "");

  const url =
    `https://generativelanguage.googleapis.com/v1beta/models/` +
    `${encodeURIComponent(cleanModel)}:generateContent`;

  const res = await fetch(url, {
    method: "POST",

    headers: {
      "Content-Type": "application/json",
      "x-goog-api-key": apiKey,
    },

    body: JSON.stringify({
      contents: [
        {
          role: "user",
          parts: [
            {
              text: prompt,
            },
          ],
        },
      ],

      generationConfig: {
        temperature: 0.3,
        maxOutputTokens,
        responseMimeType: "application/json",
      },
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");

    throw new Error(
      `Gemini API error (${res.status}): ${body.slice(0, 500)}`,
    );
  }

  const data = (await res.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{
          text?: string;
        }>;
      };
    }>;
  };

  const text = data.candidates?.[0]?.content?.parts
    ?.map((part) => part.text ?? "")
    .join("");

  if (!text) {
    throw new Error("Gemini API returned no text content.");
  }

  return text.trim();
}

/* -------------------------------------------------------------------------- */
/* Custom OpenAI-Compatible Endpoint                                          */
/* -------------------------------------------------------------------------- */

async function generateWithCustomEndpoint(
  baseUrl: string,
  apiKey: string,
  model: string,
  prompt: string,
  maxTokens = 5000,
): Promise<string> {
  const url = baseUrl.replace(/\/+$/, "") + "/chat/completions";

  const res = await fetch(url, {
    method: "POST",

    headers: {
      "Content-Type": "application/json",
      ...(apiKey
        ? {
            Authorization: `Bearer ${apiKey}`,
          }
        : {}),
    },

    body: JSON.stringify({
      model,
      max_tokens: maxTokens,
      messages: [
        {
          role: "user",
          content: prompt,
        },
      ],
    }),
  });

  if (!res.ok) {
    const body = await res.text().catch(() => "");

    throw new Error(
      `Custom AI Endpoint error (${res.status}): ${body.slice(0, 500)}`,
    );
  }

  const data = (await res.json()) as {
    choices?: Array<{
      message?: {
        content?: string | null;
      };
    }>;
  };

  const text = data.choices?.[0]?.message?.content;

  if (!text) {
    throw new Error("Custom AI Endpoint returned no text content.");
  }

  return text.trim();
}

/* -------------------------------------------------------------------------- */
/* Provider Configuration                                                     */
/* -------------------------------------------------------------------------- */

async function getProviderConfig(): Promise<ProviderConfig> {
  const configuredProvider =
    (await getSetting("ai_provider")) ||
    process.env.AI_PROVIDER ||
    "";

  const provider = configuredProvider.trim().toLowerCase();

  let apiKey = "";
  let model = "";
  let baseUrl = "";

  if (provider === "anthropic") {
    apiKey =
      (await getSetting("ai_anthropic_key")) ||
      process.env.ANTHROPIC_API_KEY ||
      "";

    model =
      (await getSetting("ai_anthropic_model")) ||
      process.env.ANTHROPIC_MODEL ||
      "claude-sonnet-4-6";
  } else if (provider === "openai") {
    apiKey =
      (await getSetting("ai_openai_key")) ||
      process.env.OPENAI_API_KEY ||
      "";

    model =
      (await getSetting("ai_openai_model")) ||
      process.env.OPENAI_MODEL ||
      "gpt-5.6-luna";
  } else if (provider === "gemini") {
    apiKey =
      (await getSetting("ai_gemini_key")) ||
      process.env.GEMINI_API_KEY ||
      "";

    model =
      (await getSetting("ai_gemini_model")) ||
      process.env.GEMINI_MODEL ||
      "gemini-3.7-flash";
  } else if (provider === "custom") {
    apiKey =
      (await getSetting("ai_custom_key")) ||
      process.env.CUSTOM_AI_KEY ||
      "";

    model =
      (await getSetting("ai_custom_model")) ||
      process.env.CUSTOM_AI_MODEL ||
      "";

    baseUrl =
      (await getSetting("ai_custom_url")) ||
      process.env.CUSTOM_AI_URL ||
      "";
  }

  /*
   * If the selected provider has no key, try environment fallbacks.
   */
  if (!apiKey) {
    if (process.env.GEMINI_API_KEY) {
      return {
        provider: "gemini",
        apiKey: process.env.GEMINI_API_KEY,
        model:
          process.env.GEMINI_MODEL || "gemini-3.7-flash",
      };
    }

    if (process.env.OPENAI_API_KEY) {
      return {
        provider: "openai",
        apiKey: process.env.OPENAI_API_KEY,
        model:
          process.env.OPENAI_MODEL || "gpt-5.6-luna",
      };
    }

    if (process.env.ANTHROPIC_API_KEY) {
      return {
        provider: "anthropic",
        apiKey: process.env.ANTHROPIC_API_KEY,
        model:
          process.env.ANTHROPIC_MODEL || "claude-sonnet-4-6",
      };
    }

    throw new AiNotConfiguredError();
  }

  return {
    provider,
    apiKey,
    model,
    baseUrl,
  };
}

/* -------------------------------------------------------------------------- */
/* Provider Dispatcher                                                        */
/* -------------------------------------------------------------------------- */

async function generateText(
  config: ProviderConfig,
  prompt: string,
  maxTokens = 5000,
): Promise<string> {
  const {
    provider,
    apiKey,
    model,
    baseUrl,
  } = config;

  if (provider === "anthropic") {
    return generateWithAnthropic(
      apiKey,
      model,
      prompt,
      maxTokens,
    );
  }

  if (provider === "openai") {
    return generateWithOpenAi(
      apiKey,
      model,
      prompt,
      maxTokens,
    );
  }

  if (provider === "gemini") {
    return generateWithGemini(
      apiKey,
      model,
      prompt,
      maxTokens,
    );
  }

  if (provider === "custom") {
    if (!baseUrl) {
      throw new Error(
        "Custom AI provider is selected but CUSTOM_AI_URL is missing.",
      );
    }

    if (!model) {
      throw new Error(
        "Custom AI provider is selected but CUSTOM_AI_MODEL is missing.",
      );
    }

    return generateWithCustomEndpoint(
      baseUrl,
      apiKey,
      model,
      prompt,
      maxTokens,
    );
  }

  throw new Error(
    `Unsupported AI provider: ${provider || "(empty)"}`,
  );
}

/* -------------------------------------------------------------------------- */
/* Public: MCQ Explanation                                                   */
/* -------------------------------------------------------------------------- */

export async function generateExplanation(
  request: ExplanationRequest,
): Promise<string> {
  const config = await getProviderConfig();

  const prompt = buildPrompt(request);

  return generateText(config, prompt, 1500);
}

/* -------------------------------------------------------------------------- */
/* Public: Flashcard Explanation                                             */
/* -------------------------------------------------------------------------- */

export async function generateFlashcardExplanation(
  request: FlashcardExplanationRequest,
): Promise<string> {
  const config = await getProviderConfig();

  const prompt = buildFlashcardPrompt(request);

  return generateText(config, prompt, 1500);
}

/* -------------------------------------------------------------------------- */
/* Public: Flashcard Set Generation                                          */
/* -------------------------------------------------------------------------- */

export async function generateFlashcardSet(
  request: FlashcardGenerationRequest,
): Promise<GeneratedFlashcard[]> {
  const count = Number(request.count);

  if (!Number.isFinite(count) || !Number.isInteger(count)) {
    throw new Error(
      "Flashcard count must be a whole number.",
    );
  }

  if (count < 1) {
    throw new Error(
      "Flashcard count must be at least 1.",
    );
  }

  if (count > MAX_FLASHCARDS) {
    throw new Error(
      `You can generate up to ${MAX_FLASHCARDS} flashcards at once.`,
    );
  }

  const hasSource =
    Boolean(request.sourceText?.trim()) ||
    Boolean(request.mcqs && request.mcqs.length > 0);

  if (!hasSource) {
    throw new Error(
      "Flashcard generation requires source material or MCQs.",
    );
  }

  const config = await getProviderConfig();

  const allCards: GeneratedFlashcard[] = [];

  /*
   * Generate in batches.
   *
   * Example:
   *
   * count = 50
   *
   * Batch 1 -> 20
   * Batch 2 -> 20
   * Batch 3 -> 10
   *
   * This avoids asking the AI to produce an enormous JSON response.
   */
  let remaining = count;

  let attempt = 0;

  while (
    allCards.length < count &&
    remaining > 0 &&
    attempt < MAX_GENERATION_ATTEMPTS + Math.ceil(count / FLASHCARD_BATCH_SIZE)
  ) {
    attempt++;

    const batchCount = Math.min(
      FLASHCARD_BATCH_SIZE,
      remaining,
    );

    const batchRequest: FlashcardGenerationRequest = {
      ...request,
      count: batchCount,
    };

    /*
     * Tell subsequent batches which questions have already been created.
     * This dramatically reduces duplicate cards.
     */
    const previousQuestions = allCards
      .map((card) => card.front)
      .join("\n");

    const batchPrompt = buildFlashcardGenerationPrompt(
      batchRequest,
    );

    const antiDuplicateInstruction =
      previousQuestions.length > 0
        ? [
            "",
            "IMPORTANT:",
            "The following flashcard questions have already been generated.",
            "Do NOT repeat or closely rephrase any of them.",
            "",
            previousQuestions,
          ].join("\n")
        : "";

    let rawResponse: string;

    try {
      rawResponse = await generateText(
        config,
        batchPrompt + antiDuplicateInstruction,
        6000,
      );
    } catch (error) {
      /*
       * If this was a temporary provider failure and we already have
       * some cards, stop cleanly with the cards we successfully generated.
       */
      if (allCards.length > 0) {
        break;
      }

      throw error;
    }

    let batchCards: GeneratedFlashcard[];

    try {
      batchCards = parseFlashcardJson(rawResponse);
    } catch (error) {
      /*
       * Retry the same batch once with a stronger JSON instruction.
       */
      const retryPrompt = [
        batchPrompt,

        "",
        "CRITICAL JSON REQUIREMENT:",
        `Return exactly ${batchCount} objects.`,
        "Return ONLY the JSON array.",
        "No markdown.",
        "No code fences.",
        "No explanation.",
        "Every object must contain both a non-empty front and back field.",
      ].join("\n");

      try {
        const retryResponse = await generateText(
          config,
          retryPrompt,
          6000,
        );

        batchCards = parseFlashcardJson(retryResponse);
      } catch {
        if (allCards.length > 0) {
          break;
        }

        throw error;
      }
    }

    const before = allCards.length;

    addUniqueCards(
      allCards,
      batchCards,
      count,
    );

    const added = allCards.length - before;

    /*
     * If the AI returned nothing new, ask again rather than looping forever.
     */
    if (added === 0) {
      if (allCards.length >= count) {
        break;
      }

      if (attempt >= MAX_GENERATION_ATTEMPTS) {
        break;
      }

      continue;
    }

    remaining = count - allCards.length;
  }

  /*
   * Return exactly the requested number when enough unique cards were
   * generated.
   */
  return allCards.slice(0, count);
}
