// Randomizes the on-screen position of an MCQ's options — the fix for
// question banks (e.g. bulk-generated by an external AI) where the correct
// option is suspiciously clustered on the same letter across many
// questions (every answer is "A", etc.), which tips students off without
// them actually knowing the material.
//
// Why this is safe to do with a pure reshuffle and nothing else:
// `mcqsTable.correctAnswer` stores the *full text* of the correct option,
// not a letter or index (see mcqsTable's own comments and mcqParser.ts,
// which resolves "Answer: C" to the matching option's text at parse time).
// Every place that checks correctness — exam scoring in exams.ts, the
// student practice/result screens, the admin edit form — compares an
// option's text against `correctAnswer`, and the A/B/C/D/E letter shown to
// students is computed on the fly from array position
// (`String.fromCharCode(65 + index)`), not stored anywhere. So reordering
// `options` automatically carries the "correct" label along with whichever
// option it belongs to; there's no separate letter field that could drift
// out of sync, and `correctAnswer` itself never needs to change.

/**
 * Shuffles `options` into a new random order and, if `optionExplanations`
 * is provided, permutes it identically so each explanation stays paired
 * with the option it explains. `correctAnswer` is untouched by design (see
 * file comment above) — the caller doesn't need to pass or update it.
 *
 * Returns `changed: false` (and the original arrays back) when there's
 * nothing meaningful to shuffle, e.g. a True/False-only "options" array of
 * length < 2 slipped through, or an edge case couldn't be reordered.
 */
export function shuffleMcqOptions(
  options: string[],
  optionExplanations: (string | null)[] | null,
): { options: string[]; optionExplanations: (string | null)[] | null; changed: boolean } {
  if (options.length < 2) {
    return { options, optionExplanations, changed: false };
  }

  const identity = options.map((_, i) => i);

  const shuffleOnce = (indices: number[]): number[] => {
    const a = [...indices];
    // Fisher-Yates
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i], a[j]] = [a[j], a[i]];
    }
    return a;
  };
  const isIdentity = (indices: number[]) => indices.every((v, i) => v === identity[i]);

  let permuted = shuffleOnce(identity);
  // A random shuffle can land back on the original order (most likely with
  // only 2-3 options) — a few retries, then a guaranteed-different fallback
  // (swap the first two slots), so "shuffle" never silently no-ops.
  for (let attempt = 0; attempt < 5 && isIdentity(permuted); attempt++) {
    permuted = shuffleOnce(identity);
  }
  if (isIdentity(permuted)) {
    permuted = [...identity];
    [permuted[0], permuted[1]] = [permuted[1], permuted[0]];
  }

  const newOptions = permuted.map((i) => options[i]);
  const newExplanations = optionExplanations
    ? permuted.map((i) => optionExplanations[i] ?? null)
    : null;

  return { options: newOptions, optionExplanations: newExplanations, changed: true };
}
