import { Router, type IRouter } from "express";
import healthRouter from "./health";
import medschoolRouter from "./medschool";
import authRouter from "./auth";
import academicStructureRouter from "./academic-structure";
import settingsRouter from "./settings";
import auditRouter from "./audit";
import uploadsRouter from "./uploads";
import pastPapersRouter from "./past-papers";
import studentToolsRouter from "./student-tools";
import analyticsRouter from "./analytics";
import studentProgressRouter from "./student-progress";
import bookReaderRouter from "./book-reader";
import mcqImportRouter from "./mcq-import";
import flashcardImportRouter from "./flashcard-import";
import mcqBackupRouter from "./mcq-backup";
import flashcardBackupRouter from "./flashcard-backup";
import siteContentRouter from "./site-content";
import examsRouter from "./exams";
import explanationsRouter from "./explanations";
import booksRouter from "./books";
import aiVisualizerRouter from "./ai-visualizer";
import adminSearchRouter from "./admin-search";
import challengesRouter from "./challenges";
import couponsRouter from "./coupons";
import ospeRouter from "./ospe";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(academicStructureRouter);
router.use(settingsRouter);
router.use(auditRouter);
router.use(uploadsRouter);
router.use(pastPapersRouter);
router.use(studentToolsRouter);
router.use(analyticsRouter);
router.use(studentProgressRouter);
router.use(bookReaderRouter);
router.use(mcqImportRouter);
router.use(flashcardImportRouter);
router.use(mcqBackupRouter);
router.use(flashcardBackupRouter);
router.use(siteContentRouter);
router.use(examsRouter);
router.use(explanationsRouter);
router.use(booksRouter);
router.use(aiVisualizerRouter);
router.use(adminSearchRouter);
router.use(challengesRouter);
router.use(couponsRouter);
router.use(ospeRouter);
router.use(medschoolRouter);

export default router;
